In [2]:
#import packages used in the code
#Good practice to do this all together and in the first cell
import numpy as np
import pandas as pd

In [3]:
#creating arrays
array_one = np.array([1,2,3])
print("Array One: ",array_one)
print("Type: ", type(array_one))

Array One:  [1 2 3]
Type:  <class 'numpy.ndarray'>

In [4]:
#creating a 2-D array

array_two = np.array([[1,2,3],[4,5,6]]) # Note the double [[]]
print(array_two)
#array characteristics
print("Size :", array_two.size)
print("Shape :", array_two.shape) #returns a tuple
print("Dims :", array_two.ndim)
print("Type :", array_two.dtype)

[[1 2 3]
 [4 5 6]]
Size : 6
Shape : (2, 3)
Dims : 2
Type : int64

In [5]:
#creating other array types

a_zeros = np.zeros((4,3))
#print(a_zeros)

a_ones = np.ones((4,5))
#print(a_ones)

a_empty=np.empty((4,4))
print(a_empty)

[[9.26898161e-310 0.00000000e+000 1.94100914e-080 3.90719476e-086]
 [5.26616473e-090 7.48269334e+247 4.08624842e-080 5.23496514e+180]
 [2.38234097e+233 1.08540613e-071 1.33498114e-046 1.20070123e-089]
 [4.10413611e+232 1.04971939e+214 8.88782220e+252 5.75436584e-268]]

In [6]:
a_r = np.arange(12)
print(a_r)

a_rs = a_r.reshape(3,4) # (rows, columns)
print(a_rs)
print()

a_rs2=np.delete(a_rs, 1, axis=1)
print (a_rs2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]

In [7]:
print(a_rs)
a = a_rs[1,1]
print("a",a)
b = a_rs[1,:] #select row 1,  ":" is not necessary
print("b",b)
c= a_rs[:,2] #select row 1 ":" is necessary
print("c",c)
d = a_rs[0:2,2:4]
print("d")
print(d)

e= np.delete(a_rs, 1, axis=0)
print("e")
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a 5
b [4 5 6 7]
c [ 2  6 10]
d
[[2 3]
 [6 7]]
e
[[ 0  1  2  3]
 [ 8  9 10 11]]

In [8]:
#Methods

print(a_rs)
print(a_rs.sum())
print(a_rs.sum(axis=0))
print(a_rs.sum(axis=1))

#Function

print(np.sum(a_rs))
print(np.sum(a_rs,0))
print(np.sum(a_rs,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
66
[12 15 18 21]
[ 6 22 38]

In [9]:
a_one =np.ones((3,3))*3
a_two = np.arange(9)
a_two = a_two.reshape(3,3)

print (a_one)
print (a_two)

a_bool = (a_one>a_two)

print(a_bool)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ True  True  True]
 [False False False]
 [False False False]]

In [10]:
data_frame = pd.DataFrame([10,20,30,40])

print(data_frame)

df_two = pd.DataFrame([[43, 'IE'],[25, 'GB'],[23,'IE']])

print ()
print (df_two)

    0
0  10
1  20
2  30
3  40

    0   1
0  43  IE
1  25  GB
2  23  IE

In [11]:
df_two = pd.DataFrame([[43, 'IE'],[25, 'GB'],[23,'IE']],
                     columns=['Age','Nationality'],
                     index = ['a','b','c'])

print(df_two)

   Age Nationality
a   43          IE
b   25          GB
c   23          IE

In [12]:
df_two.info()

<class 'pandas.DataFrame'>
Index: 3 entries, a to c
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          3 non-null      int64
 1   Nationality  3 non-null      str
dtypes: int64(1), str(1)
memory usage: 72.0+ bytes

In [13]:

print(df_two.describe())
#df_two.describe()

             Age
count   3.000000
mean   30.333333
std    11.015141
min    23.000000
25%    24.000000
50%    25.000000
75%    34.000000
max    43.000000

In [14]:
df_two.head()

   Age Nationality
a   43          IE
b   25          GB
c   23          IE

In [15]:
#df_two.index
#print(df_two.columns)

print(df_two)
#print(df_two.loc['b'])
#print(df_two.loc['b','Age'])
#print(df_two.loc[['b','c']])
#print(df_two.loc[['b','c'],'Age'])

#print(df_two.Age)
#x=df_two.Age
#print(x)

print(df_two.iloc[0:2])
print(df_two.iloc[:,1])

   Age Nationality
a   43          IE
b   25          GB
c   23          IE
   Age Nationality
a   43          IE
b   25          GB
a    IE
b    GB
c    IE
Name: Nationality, dtype: str

In [16]:
np_one = np.arange(9)
np_one = np_one.reshape((3,3))

print(np_one)

pd_one = pd.DataFrame(np_one)
pd_one.info()
pd_one.head()

pd_one.columns=['c1','c2','c3']
pd_one.head()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       3 non-null      int64
 2   2       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

   c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8

In [17]:
print(pd_one.mean())
print(pd_one.mean(axis=0))
print(pd_one.mean(axis=1))
print(pd_one.c1.mean())
print(np.mean(pd_one))

c1    3.0
c2    4.0
c3    5.0
dtype: float64
c1    3.0
c2    4.0
c3    5.0
dtype: float64
0    1.0
1    4.0
2    7.0
dtype: float64
3.0
4.0